/**
 * EDI Normalizer Example
 *
 * This example demonstrates how to:
 * 1. Read parsed EDI transactions from JSON files in the output directory
 * 2. Use the NormalizerFactory to create a normalizer for 271 transactions
 * 3. Normalize transactions into business-friendly Eligibility objects
 * 4. Display the normalized results
 *
 * The output directory contains JSON files with parsed EDI transactions
 * generated by the edi-parser-example.
 */

import * as fs from "fs";
import * as path from "path";
import {
  NormalizerFactory,
  EligibilitySchema,
  type EDITransaction,
  type Eligibility,
} from "@edi-parser/core";

/**
 * Interface for the JSON file structure in the output directory
 */
interface ParsedTransactionFile {
  sourceFile: string;
  timestamp: string;
  transaction: EDITransaction;
  parseStatistics: unknown;
}

/**
 * Recursively find all JSON files in a directory
 */
function findJsonFiles(dir: string, fileList: string[] = []): string[] {
  const files = fs.readdirSync(dir);

  for (const file of files) {
    const filePath = path.join(dir, file);
    const stat = fs.statSync(filePath);

    if (stat.isDirectory()) {
      // Recursively search subdirectories
      findJsonFiles(filePath, fileList);
    } else if (file.endsWith(".json")) {
      // Add JSON files to the list
      fileList.push(filePath);
    }
  }

  return fileList;
}

/**
 * Main function to process and normalize transactions
 */
function main(): void {
  console.log("🔄 EDI Normalizer Example");
  console.log("=".repeat(80));

  // Get the input directory path
  const inputDir = path.join(__dirname, "edi-normalizer-example", "input");

  // Check if input directory exists
  if (!fs.existsSync(inputDir)) {
    console.error("❌ Input directory not found:", inputDir);
    console.log("\n💡 Run the parser example first:");
    console.log("   npm run example:edi-parser");
    return;
  }

  // Clear output directory before processing
  const outputBaseDir = path.join(
    __dirname,
    "edi-normalizer-example",
    "output",
  );
  if (fs.existsSync(outputBaseDir)) {
    console.log("🧹 Clearing output directory...");
    fs.rmSync(outputBaseDir, { recursive: true, force: true });
  }
  fs.mkdirSync(outputBaseDir, { recursive: true });

  // Recursively find all JSON files from the input directory
  const files = findJsonFiles(inputDir);

  if (files.length === 0) {
    console.error("❌ No JSON files found in input directory");
    console.log("\n💡 Run the parser example first:");
    console.log("   npm run example:edi-parser");
    return;
  }

  console.log(`\n📁 Found ${files.length} parsed transaction file(s)`);
  console.log("-".repeat(80));

  // Create the normalizer factory and get a 271 normalizer
  const factory = NormalizerFactory.getInstance();
  const normalizer = factory.createNormalizer("271");

  console.log("\n✅ Created EDI 271 Normalizer");
  console.log(
    `📋 Supported transaction types: ${factory.getSupportedTransactionTypes().join(", ")}`,
  );

  // Process each file
  let successCount = 0;
  let errorCount = 0;

  for (const filePath of files) {
    // Get relative path for display
    const relativeFilePath = path.relative(inputDir, filePath);

    try {
      console.log(`\n📄 Processing: ${relativeFilePath}`);

      // Read and parse the JSON file
      const fileContent = fs.readFileSync(filePath, "utf8");
      const parsedData = JSON.parse(fileContent) as ParsedTransactionFile;

      // Extract the transaction
      const transaction = parsedData.transaction;

      console.log(`   Source: ${parsedData.sourceFile}`);
      console.log(`   Transaction Type: ${transaction.transactionType}`);
      console.log(`   Control Number: ${transaction.controlNumber}`);
      console.log(`   Segments: ${transaction.segments.length}`);
      console.log(`   Loops: ${transaction.loops.length}`);

      // Check if normalizer supports this transaction type
      if (!normalizer.supports(transaction)) {
        console.log(
          `   ⚠️  Skipped: Normalizer does not support transaction type ${transaction.transactionType}`,
        );
        errorCount++;
        continue;
      }

      // Normalize the transaction
      const startTime = performance.now();
      const eligibility = normalizer.normalize(transaction) as Eligibility;
      const endTime = performance.now();

      console.log(`   ✅ Normalized in ${(endTime - startTime).toFixed(2)}ms`);

      // Validate normalized output against schema
      const validationResult = EligibilitySchema.safeParse(eligibility);
      if (!validationResult.success) {
        console.error(`   ❌ Schema validation failed:`);
        console.error(
          `      ${validationResult.error.errors.map((e: { path: (string | number)[]; message: string }) => `${e.path.join(".")}: ${e.message}`).join("\n      ")}`,
        );
        errorCount++;
        continue;
      }
      console.log(`   ✅ Schema validation passed`);

      // Display normalized results
      displayEligibilityResults(eligibility);

      // Create output directory preserving folder structure
      const outputFilePath = path.join(
        __dirname,
        "edi-normalizer-example",
        "output",
        relativeFilePath.replace(".json", "-normalized.json"),
      );
      const outputDir = path.dirname(outputFilePath);

      if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
      }

      // Save normalized output
      fs.writeFileSync(
        outputFilePath,
        JSON.stringify(
          {
            sourceFile: parsedData.sourceFile,
            normalizedAt: new Date().toISOString(),
            eligibility,
          },
          null,
          2,
        ),
        "utf8",
      );
      console.log(
        `   💾 Saved: ${relativeFilePath.replace(".json", "-normalized.json")}`,
      );

      successCount++;
    } catch (error) {
      console.error(
        `   ❌ Error processing ${path.relative(inputDir, filePath)}:`,
        error,
      );
      errorCount++;
    }
  }

  // Display summary
  console.log("\n" + "=".repeat(80));
  console.log("📊 Summary");
  console.log("=".repeat(80));
  console.log(`✅ Successfully normalized: ${successCount}`);
  console.log(`❌ Errors: ${errorCount}`);
  console.log(`📁 Total files processed: ${files.length}`);
}

/**
 * Display normalized eligibility results in a formatted way
 */
function displayEligibilityResults(eligibility: Eligibility): void {
  console.log("\n   📋 Normalized Eligibility:");

  // Payer Information
  if (
    eligibility.payer?.name !== undefined &&
    eligibility.payer?.name !== null &&
    eligibility.payer?.name.length > 0
  ) {
    console.log(`      Payer: ${eligibility.payer.name}`);
  }
  if (
    eligibility.payer?.payerIdCode !== undefined &&
    eligibility.payer?.payerIdCode !== null &&
    eligibility.payer?.payerIdCode.length > 0
  ) {
    console.log(`      Payer ID: ${eligibility.payer.payerIdCode}`);
  }

  // Provider Information
  if (
    (eligibility.provider?.npi !== undefined &&
      eligibility.provider?.npi !== null &&
      eligibility.provider?.npi.length > 0) ??
    (eligibility.provider?.providerId !== undefined &&
      eligibility.provider?.providerId !== null &&
      eligibility.provider?.providerId.length > 0)
  ) {
    console.log(
      `      Provider: ${eligibility.provider?.npi ?? eligibility.provider?.providerId}`,
    );
  }

  // Subscriber Information
  if (
    (eligibility.subscriber?.firstName !== undefined &&
      eligibility.subscriber?.firstName !== null &&
      eligibility.subscriber?.firstName.length > 0) ??
    (eligibility.subscriber?.lastName !== undefined &&
      eligibility.subscriber?.lastName !== null &&
      eligibility.subscriber?.lastName.length > 0)
  ) {
    const subscriberName = [
      eligibility.subscriber?.firstName,
      eligibility.subscriber?.lastName,
    ]
      .filter(Boolean)
      .join(" ");
    console.log(`      Subscriber: ${subscriberName}`);
  }
  if (
    eligibility.subscriber?.memberId !== undefined &&
    eligibility.subscriber?.memberId !== null &&
    eligibility.subscriber?.memberId.length > 0
  ) {
    console.log(`      Member ID: ${eligibility.subscriber.memberId}`);
  }

  // Patient Information
  if (
    (eligibility.patient?.firstName !== undefined &&
      eligibility.patient?.firstName !== null &&
      eligibility.patient?.firstName.length > 0) ??
    (eligibility.patient?.lastName !== undefined &&
      eligibility.patient?.lastName !== null &&
      eligibility.patient?.lastName.length > 0)
  ) {
    const patientName = [
      eligibility.patient?.firstName,
      eligibility.patient?.lastName,
    ]
      .filter(Boolean)
      .join(" ");
    console.log(`      Patient: ${patientName}`);
  }

  // Plan Information
  console.log(`      Plan Status: ${eligibility.plan.planStatus}`);
  if (
    eligibility.plan.planName !== undefined &&
    eligibility.plan.planName !== null &&
    eligibility.plan.planName.length > 0
  ) {
    console.log(`      Plan Name: ${eligibility.plan.planName}`);
  }
  if (eligibility.plan.insuranceType) {
    console.log(`      Insurance Type: ${eligibility.plan.insuranceType}`);
  }

  // Benefits
  if (eligibility.plan.benefits && eligibility.plan.benefits.length > 0) {
    console.log(
      `      Benefits: ${eligibility.plan.benefits.length} benefit(s)`,
    );
  }

  // Deductibles
  if (eligibility.plan.deductibles && eligibility.plan.deductibles.length > 0) {
    console.log(
      `      Deductibles: ${eligibility.plan.deductibles.length} deductible(s)`,
    );
    for (const deductible of eligibility.plan.deductibles.slice(0, 3)) {
      if (deductible.amount !== undefined) {
        const networkType = deductible.network?.networkType;
        const networkInfo =
          networkType !== undefined &&
          networkType !== null &&
          networkType.length > 0
            ? ` (${networkType})`
            : "";
        console.log(
          `         - $${deductible.amount.toFixed(2)}${networkInfo}`,
        );
      }
    }
  }

  // Maximums
  if (eligibility.plan.maximums && eligibility.plan.maximums.length > 0) {
    console.log(
      `      Maximums: ${eligibility.plan.maximums.length} maximum(s)`,
    );
    for (const maximum of eligibility.plan.maximums.slice(0, 3)) {
      if (maximum.amount !== undefined) {
        const networkType = maximum.network?.networkType;
        const networkInfo =
          networkType !== undefined &&
          networkType !== null &&
          networkType.length > 0
            ? ` (${networkType})`
            : "";
        console.log(`         - $${maximum.amount.toFixed(2)}${networkInfo}`);
      }
    }
  }
}

// Run the example
main();
